services:
  - type: web
    name: halligalli-online
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start -w server
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
